# Generated by Django 3.1.3 on 2023-12-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='order_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
